controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

auth_controllers:
    resource:
        path: ../src/Auth/Infrastructure/Controller/
        namespace: App\Auth\Infrastructure\Controller
    type: attribute
