<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYsSLMuj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYsSLMuj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYsSLMuj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYsSLMuj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYsSLMuj\App_KernelDevDebugContainer([
    'container.build_hash' => 'YsSLMuj',
    'container.build_id' => '9cc1fb63',
    'container.build_time' => 1731595327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYsSLMuj');
