<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOQFxwZ4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOQFxwZ4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOQFxwZ4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOQFxwZ4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOQFxwZ4\App_KernelDevDebugContainer([
    'container.build_hash' => 'OQFxwZ4',
    'container.build_id' => 'f9d87a5d',
    'container.build_time' => 1731595259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOQFxwZ4');
