<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcoDrpj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcoDrpj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJcoDrpj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJcoDrpj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJcoDrpj\App_KernelDevDebugContainer([
    'container.build_hash' => 'JcoDrpj',
    'container.build_id' => 'fddd034b',
    'container.build_time' => 1731595358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcoDrpj');
